### ISSUE TITLE
all are negative

### ISSUE THREAD

**Issue by DerXanRam** [jrbjrb1212/Cpp-Crypto-Arbitrage-Framework#2]
i run the bot for 2 days in debug mode and every profit path the bot find have "-" sign. all the ROI, profitable, and EXprice have "-" sign. is it negative or a "separetor"...i just confused. also what is EXprice and are the ROI numbers are percentage? 

tnx very much![Screenshot_20230520-095219.jpg](https://github.com/jrbjrb1212/Cpp-Crypto-Arbitrage-Framework/assets/101794261/dd2d473f-a7f1-4dd7-b034-6dce0a5de12f)

**Comment by jrbjrb1212** [comment]
Hello,

**Thank you for checking out my project and posting this issue!** 

I will answer your questions in two parts.

**1. The meaning of "-" in the above debug information.**
- The negative sign in your screenshot indicates that after a profitable arbitrage path was identified by ticker data (best prices) it was proved to be unprofitable by pulled order book (actual prices) information. This happens pretty frequently in detecting arbitrage opportunities as can be short-lived (only are alive for a few seconds) or the ticker data is outdated. The order book data is actual market orders in the market.
- This type of thing happens all the time where a trade looks profitable by ticker data (best prices) but it completely unprofitable by actual trades in the market. There is a much higher frequency of this happening with smaller coins that have low liquidity (only a small amount of trade everyday)

**2. Term/Variable definitions** 
- First off, thank you for pointing out my sloppy mistake. Your screenshot points out that I forgot to differentiate ROI and profitability. I will create an updated commit later this week with better information.
- **EXprice** is the ticker data price point listed by the exchange. Basically, it is the best bid or ask price for a given trading pair. All of the original values are natural logged to help with numerical stability. EX: USDT->BTC is about 27,000 UST -> 1 BTC. The 27,000 gets natural logged so the value is about +10.2 when going from BTC to USDT and about -10.2 going from USDT to BTC.
- **Profitability** is the raw profit earned in log representation. If you started with 10 USDT (2.3 in log) and ended with 11 USDT (2.4 in log), profitability would be the difference between the original and after the arbitrage so 1 USDT. To answer your question, no profitability is not a percentage.
- **ROI** is the percentage of profit expected by trading on the arbitrage opportunity. With the example above, you would have a 10% ROI. To answer your question, ROI should be a percentage but it is currently not.

If this project does interest you, feel free to develop out a feature, refactor some code, or change some part of my code and submit a PR. I would love to get a more diverse set of coding skills on this project.

Let me know if you have any other questions.

I will close this issue at the end of the week when I update the debug print statements.

--John

**Comment by DerXanRam** [comment]
Hello. Thanks for the answers.🙏 now i understand the readings. Also i am working on your project to add a feature that executes  order following the path founded. It is a little bit hard cause this is the first time I try to communicate with API endpoint using c++.I will push request if i can implement it successfully.

Thanks veery much for this framework.
