### ISSUE TITLE
Cross exchange

### ISSUE THREAD

**Issue by DerXanRam** [jrbjrb1212/Cpp-Crypto-Arbitrage-Framework#4]
Hello John. I see somthing when i read your readme.md. In "Disclaimer and Drawbacks" section you mentioned that few exchanges allow cross exchange trade. Can u tell me their name please?

Thanks

---Der

**Comment by jrbjrb1212** [comment]
Hi Der,

Great to see you again! Bitget and Kraken had an agreement for a while that enabled fast transfer of assets (under a second) for a low price. Binance and Coinbase have a current agreement for instant honoring of assets. Although Coinbase charges a default rate for each transaction that is not based on size, so it would be less efficient. It is better when you have Coinbase Pro but still not great.

It is one of the main killers of the speed of acting on a particular arbitrage. Have you looked into parallel execution of different parts of a specific detected arbitrage by having assets on multiple exchanges? 

Hope any of the above helps,
John

**Comment by jrbjrb1212** [comment]
Hi Der,

Just wanted to also let you know that I finally got around to cleaning up the code. I think I told you I would do this back in May, so I apologize for the delay!!!

Feel free to pull from the updated repo and it work in a more streamlined way. 

--John

**Comment by DerXanRam** [comment]
> Hi Der,
> 
> Just wanted to also let you know that I finally got around to cleaning up the code. I think I told you I would do this back in May, so I apologize for the delay!!!
> 
> Feel free to pull from the updated repo and it work in a more streamlined way. 
> 
> --John

Hello john... I'm Happy to see u online. I thought u left this project abandoned .

Thanks very much for your answer will check them up the exchanges and look ur changes on ur code.

A week ago i was successfully implemented arbitrage only inside binance spot. The results was crazy. I gave 57.4 USDT for the bot and by the end of the day it changed to 61.2 USDT. I was analyzing the results every 6 hour and almost all profits comes from specific combinations like USDT-TLM-BTC-USDT, USDT-BAKE-BNB-USD .......and othet 15 combinations. Then aftet 2 days, on aug 4, binance announced that the removal of some specific liquidity pools. When i see the list i amazed. All the combinations i identified as profitable combinations are removed😄. Here is the announcement [link](https://www.binance.com/en/support/announcement/notice-regarding-the-removal-of-selected-liquidity-pools-on-binance-liquid-swap-2023-08-04-1b01b15e40054bc4868e4b9713cced80).

Any way the arbitarge bot i built is very different  from yours interms of implementation and algorithm. It contains main.cpp and no header files. So i didn't pull request here.

Anyway i will share my code and real results(screenshots, logs...) here.

Thanks very much🙏🙏🙏. Your project initiated me to discover this amazing, low risk trading strategy. I also improved my cpp skill.

--Det

**Comment by DerXanRam** [comment]
> > Hi Der,
> > 
> > Just wanted to also let you know that I finally got around to cleaning up the code. I think I told you I would do this back in May, so I apologize for the delay!!!
> > 
> > Feel free to pull from the updated repo and it work in a more streamlined way. 
> > 
> > --John
> 
> Hello john... I'm Happy to see u online. I thought u abandoned this project.
> 
> Thanks very much for your answer will check them up.
> 
> A week ago i was successfully implemented arbitrage only inside binance liquidity swap. The results was crazy. I gave 57.4 USDT for the bot and by the end of the day it changed to 61.2 USDT. I was analyzing the results every 6 hour and almost all profits comes from specific combinations like USDT-TLM-BTC-USDT, USDT-BAKE-BNB-USD .......and othet 15 combinations. Then aftet 2 days, on aug 4, binance announced that the removal of some specific liquidity pools. When i see the list i amazed. All the combinations i identified as profitable combinations are removed😄. Here is the announcement [link](https://www.binance.com/en/support/announcement/notice-regarding-the-removal-of-selected-liquidity-pools-on-binance-liquid-swap-2023-08-04-1b01b15e40054bc4868e4b9713cced80).
> 
> Any way the arbitarge bot i built is very different  from yours interms of implementation and algorithm. It contains main.cpp and no header files😄. So i didn't pull request here.
> 
> Anyway i will share my code and real results(screenshots, logs...) here.
> 
> Thanks very much🙏🙏🙏. Your project initiated me to discover this amazing, low risk trading strategy. I also improved my cpp skill.

![Screenshot_20230803-172216.jpg](https://github.com/jrbjrb1212/Cpp-Crypto-Arbitrage-Framework/assets/101794261/e5fc732a-5cc9-4f0f-93d2-2e17d46a0ad3)

![Screenshot_20230803-172235.jpg](https://github.com/jrbjrb1212/Cpp-Crypto-Arbitrage-Framework/assets/101794261/a5dd70d6-f67a-4600-b324-a22169ce8699)

![Screenshot_20230803-172229.jpg](https://github.com/jrbjrb1212/Cpp-Crypto-Arbitrage-Framework/assets/101794261/d0f94deb-9d1e-4933-9b30-cc531ed42538)

![Screenshot_20230803-172245.jpg](https://github.com/jrbjrb1212/Cpp-Crypto-Arbitrage-Framework/assets/101794261/c3e53759-492c-48d7-99b5-1b6d6015a948)

Balance changing from 57usdt to 61 usdt.
"convert" in the screenshot is also the result of the bot. not from other source.

Images are not in order!!!

**Comment by jrbjrb1212** [comment]
Hi Der,

That is great to hear! I am happy that my work gave you a good launch pad to make your own algorithm and trading bot. Please drop a comment on this issue when you end up publicly releasing it. Or, if you don't plan on releasing it publicly feel free to add me a viewer on the private repo. I would love to see how your version of the bot given that you have demonstrated profitability.

Back in April, I was able to use my framework to get about 30% profit in one day from an arbitrage detected between binance and gate.io for BTC and ETH, but it required a lot of manually checking detected arbitrages. 

Also, if you have a future idea about crypto arbitrages or anything adjacent in the finance data space, feel free to ping me. I am always picking up random projects like this one.

Great work again getting your own algo and bot up and running!!! That is very cool!

--John

**Comment by DerXanRam** [comment]
> Hi Der,
> 
> That is great to hear! I am happy that my work gave you a good launch pad to make your own algorithm and trading bot. Please drop a comment on this issue when you end up publicly releasing it. Or, if you don't plan on releasing it publicly feel free to add me a viewer on the private repo. I would love to see how your version of the bot given that you have demonstrated profitability.
> 
> Back in April, I was able to use my framework to get about 30% profit in one day from an arbitrage detected between binance and gate.io for BTC and ETH, but it required a lot of manually checking detected arbitrages. 
> 
> Also, if you have a future idea about crypto arbitrages or anything adjacent in the finance data space, feel free to ping me. I am always picking up random projects like this one.
> 
> Great work again getting your own algo and bot up and running!!! That is very cool!
> 
> --John
> 

Hello John.

Tnx for replying .... i will release publicly and share the link here. Also I am amazed by 30% profit u gained by one day.

Der

**Comment by DerXanRam** [comment]
and user setting generator is not working properly. The previous version works without any problem. Here is the result
`Traceback (most recent call last):
  File "/root/Cpp-Crypto-Arbitrage-Framework/Framework/Symbol_Data_Files/request_coingecko_api.py", line 173, in <module>
    main()
  File "/root/Cpp-Crypto-Arbitrage-Framework/Framework/Symbol_Data_Files/request_coingecko_api.py", line 161, in main
    viable_coins = scrape_pages(number_coins_req, min_coin_vol)
  File "/root/Cpp-Crypto-Arbitrage-Framework/Framework/Symbol_Data_Files/request_coingecko_api.py", line 63, in scrape_pages
    parse_coin_from_json(json_coins_data, viable_coins, min_vol)
  File "/root/Cpp-Crypto-Arbitrage-Framework/Framework/Symbol_Data_Files/request_coingecko_api.py", line 16, in parse_coin_from_json
    for coin_data in json_data:
TypeError: 'NoneType' object is not iterable
mv: cannot stat 'Viable_Trading_Pairs.txt': No such file or directory
user_settings are generated
building framework`
